database:
  path: notes.db
server:
  host: 0.0.0.0
  port: 8000
oauth:
  client_id: your_client_id
  client_secret: your_client_secret
  auth_url: https://auth-provider.com/authorize
  token_url: https://auth-provider.com/token